travis:
  secure:
    BINSTAR_TOKEN: wkSjj8UpJItvsGhRZDX3cmsLQ5TOKGfHg9bO383Q+7iOW6+8mDCs5taygIhfhVJjVMekc30grPxnpkId2lZSJBbvUpG6tbYvQI8U3VIc+yNxljoGUc9fFFBJ0zqsyOzstjPtudf2Vn3MVlx9QyPA9Kiji3fVQrwrG5Ncess6cDkI9Lmyc5POP1nXCntqylmhuDw3NNKp6zVY5AfNrVopGT3awf4cxT7Fxvs9T3nBXNyXYCOjGuDWohrdKTv3lwRXjCcIReo01avsF+Z2moRGpMZYnKWsHF+MGjYWfUj1/DjJZ3DKhqlin/PdgganzKTOQea/srR3nwXsq08L8RY/8jayN27ONHTX9XzBygVE/MyRsjGClONqI/rwP6nTzcjIvj+QGYf+39+qcznVmjsOcwG/gAZv0C0F1xR0PPaLmMJG835G2pnit0BUq3WI1Fa8h8vkNQnmAQ6jBZgE+222UeRnM48Odb41B3ULlDjv+7x6LWBdOV6jkowwfSOHO13cK9lFIhWENMGdT2zIXiaovklB9YrB12eIhXWG9fSXMgqN/ndXS4U3gyMDZ656F3NzzrDPdZg+KXreVq99BA/bLHDqnyWuljJ7Jz06y+WlMLw4EXMbkWtMF8CODnGiy1qzvMHFc/bju4sCvBWveS1zSqLg787/qCzIh5qLk77XKYc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
