travis:
  secure:
    BINSTAR_TOKEN: Cm0RS4k2igpCTgsBl6JWZHTA08yzAgE7N/srEtX56EMT6Vxphip3vxC5r5tsj4HL0ytkPg3GC8d4SEiLhNCduASNQLUmqOtFSLGHNKTEqPxXCrAqlpQo8OgdilNIA3sbc0S23ZcB18OjMUagZezKMgbzDVGSbtCK67fKrR96ZaN0tDUEQVgmMS+KTRy471rSSUfsGl/qMA259cjXUSsmeF5IOg8s3RhmXoN1qmsJob0wDVXrmUlFJyBzcoP5xJ+zOTR7feG2SjZUXAIeB1zX8OyEZ3V7vYOnjckGmXG+SMzu7kktTQrpXhwYE2fZPX2fXhrScEwwARzDIptdiELmmaFxIOre84yI27BiLKF8bxBAjNbWx7qQddzn9KkPWv/Gk+pCtk614BnfYy9kA6D67tEY2tnyvd65bs1/IiZhuS3vvLPC/Ujdz+BqVIK6v57Bt29Nb68x/mzoB8YLL4+LnY+/Fac6lOsusZ7AXWmxsUC1SX1henLwJfJFLcVtroMBcG6CqIIK01QBDs+YoVVdgrLmEhSR6yV9vtrVSUvX4NKSkvDvhgv2Pq/6ZuLNk29pw3cmmFKiFEmJoLsYKZRIAQB1SE3Ld5mken4XnPJB0oCCeYafZIMhaIe5YNX/l+4azSF6tPb79IrFPlZnhSmNzIS4wx0Rgt9SP7OlOu/oIzk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
