travis:
  secure:
    BINSTAR_TOKEN: FOcHu6Ut2KkeVbHs8ZK54uUfJSl4htT8OBH6zSf5I11relCSwxzssQ/bMooC0ss5BfcCCgWi9MN3wtd4vH+MMF10RFvY/OPfizEo86tEbmEtaQolJvyvB2K2Gsvs/ZUriEH926kGUeZNblxkxOyDRuFi41vAKLeQetRNGdWA2lpiRlpMDotxhnm4GFGQh8U1gL8kfeAd8lrhsAzvBWigVpMpi4j/xIr9pE7cLQMmz3bACW64t44RMk9/r3Xe5SWbqR/JZQvPyPlMu84mSPCP6xr17wQLwFo9QV2wZia7Eus5hTL4aPbZZcI1W+xxhdaVUcE6CmwnRW/R+2fYOTqTobK3Ce0/EUAvcV6CULjrcXdPaeOMt1cp6rYkNlTp37/DimDbwaefhdfOFqVXpPGa1P4g6iitU919g1IJ86SM7JWAdcBmKHsXYDqNtFCGsIEYk6AZQ0rdB2g65eCLspC3a1PeK+/aLRoxzmAePQvi04B/587WVGdqUHiLdymGW6nX7y7XI0gwVRJbQ3/vEiTIT0FemqF1sPDt82McjCCc51hQZOGafGufXS0kgmaFn/tI6p89TdNwbMJqCm+wJwmGnF02cBBwWZCM7JfRpNSyyF7UA9R8covRQp/F9V0iS0WxsThl90/bYtGG0yTpXvOw0xDRqRLYVeGAHxUTtfqBbmQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
