travis:
  secure:
    BINSTAR_TOKEN: L43cgoIQkvZ9p0AsWxno81QP+xWYPhY0VZ2o4Em2dR9+5W49/VUZxA2+QmunAX7Mybe3vz90AFogxYY+moag8JexspSNlV1loOBXAGfCLG17G87En0l9W6Ih6LKbKgAP+JDeUL+sRZOxqPvuO8GSyphhG1vRw8+w7Mw+aFiwh1yUKyB0QD7FE3OI2lTAmBqMMkjwYpPZo8I1evQ67wkMjNJiOW32sYich5mi/jmNCPF8MJ0yzjqJcOFDisHhR1Q2ftmKuLsSc4SDMgi9imVOuy8yQIoyAJafi1URZrw/+oY3LNT3UGmg23xfEXPOWD1kPEvtKDO55AQSaD1Qn6iVpquSRhTJY62fm3QmW20fEUe+BzwiXmHu3O94y+EuihYbd/l7NVfbezsOUBunmVzfgQn/ePlY8E9QL4j801iac8n/0aTAQPdgmJ21hbmhfZNozzgADe1ItIA9tdKao6U4q3HaKbjYm5v/cozsDvuZYpFdvzmpF7C3TneOSOusekw/0vFkKVh5oKpoWtVPKMaDfX8/GguJ0nBi2cRzb3UyNl6mSzrfyyY69/w69YvtDsM9GSf5TY4O0UhALPUFvpx4vag9RxOSvM01TJKlp5hd9i38PtUtjx9BDsMdZ/wdUZ/WC0RwoHv6M6xq36cDg+z0S87zxmKAXVKLPHTO+UMuUvg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
