travis:
  secure:
    BINSTAR_TOKEN: hownVhA5HP0RaSdxa3/2aviSgrGcqNRsjo5RKWPMJ//g/r+I/1sIMxAZy1Y1J/gcrIfJQ6VRew0vcGSn5j7jRoLECpx/uRnFdVlH2oX49oe8UQr97d2i1wDe56DY3TSC25aiqGaFZpISsYpZVzA1kyB2jir7NYxQr8JWfHrevJjiMcPliIVvAk+SPlag+594tuCm0/GPVEFyswr/fJlJPS0Vx/8nsHCJ0nK/f0U2LOVKtwxGxYE8uRatXoat2QzIK1SxIB5fVyRxfxNpyu9t+SxZs9tTYlkkI+/wOB+ViRdbbH/EmzWXffE6+cIwX8QlCMRYhvHJe5ixJ7W9XBwV43OOU3DkFag5OJ82Itg+DNSIEQHf1DGLZrry77jHFGShWO2BRSVk29lePtgbUHd2Vka6HyBIrENc0IC80losXUurg+rmXNK1+atw/TK2kxhg3SajdFFn2LuyfRU40PohVFLsnVRcolosKt6w5htak2mgHWhxHcXj311xknaI1OjwSgI87V8Wum/0XIpXPYGIMr+Mo8SM58wxPfHukXWa9pPz82lcvFAHw4XxN8YWg4mcG1K5aqbtllgquDVJF81egSPYtPP8RwdLzdS+g2eTRZoNey0bj+qVzfH0KcNsyL+04VMl250osASdViwfCLyu9QtKisavGllVDu7iyoKphtY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
